spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: team_g
    password: green502
    jdbc-url: jdbc:mariadb://192.168.0.144:3306/team_g

mybatis:
  type-aliases-package: com.green.boardver3
  mapper-locations: mapper/**/*.xml

# swgger
springdoc:
  swagger-ui:
    path: /swagger.html

file:
  dir: D:/download/board3
